%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.27.4

-ifndef(request_for_connect_pb).
-define(request_for_connect_pb, true).

-define(request_for_connect_pb_gpb_version, "3.27.4").

-ifndef('REQUEST_FOR_CONNECT_PB_H').
-define('REQUEST_FOR_CONNECT_PB_H', true).
-record(request_for_connect,
        {ua                     :: binary() | iolist() | undefined, % = 1
         pubkey                 :: binary() | iolist() | undefined % = 2
        }).
-endif.

-endif.
