%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.27.4

-ifndef(request_for_add_pc_tail_pb).
-define(request_for_add_pc_tail_pb, true).

-define(request_for_add_pc_tail_pb_gpb_version, "3.27.4").

-ifndef('REQUEST_FOR_ADD_PC_TAIL_PB_H').
-define('REQUEST_FOR_ADD_PC_TAIL_PB_H', true).
-record(request_for_add_pc_tail,
        {ua                     :: binary() | iolist() | undefined, % = 1
         encoded_pc_tail        :: binary() | iolist() | undefined % = 2
        }).
-endif.

-endif.
